### ISSUE TITLE
DisplayContentBehindBars

### ISSUE THREAD

**Issue by FM1973** [RadekVyM/SimpleToolkit#13]
Hello.

I´m trying to use the DisplayContentBehindBars function in my app.
On IOS, the statusbar is being displayed transparent as expected.
On Android it´s being displayed WHITE.

I know your Marvelous sample and in your sample the code works on android as well. I tried to figure out if I was missing something, but didn´t find any significant difference. One thing: I´m not using your shell implementation.

Is there anything special I missed one has to do to get ir running on android?

Thanks for your help!

**Comment by RadekVyM** [comment]
Hi @FM1973,
thanks for finding the bug. I hope I found the issue and fixed it. You can try [the newest version of the package](https://www.nuget.org/packages/SimpleToolkit.Core/2.0.4).
