### ISSUE TITLE
Shell search handler ? 

### ISSUE THREAD

**Issue by Strypper** [RadekVyM/SimpleToolkit#22]
Hi does this support shell search? because when I migrate from the built-in Shell the Shell Search disappeared

**Comment by RadekVyM** [comment]
Hi @Strypper,
`SimpleShell` on its own does not provide any controls. All navigation related controls have to be custom made. You can create your own search view and bind it to the `Shell.SearchHandler` [properties](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.searchhandler).
