### ISSUE TITLE
How to navigate from tap gesture?

### ISSUE THREAD

**Issue by raselldev** [RadekVyM/SimpleToolkit#30]
i have .xaml like this:

```
  <Label.GestureRecognizers>
      <TapGestureRecognizer
          x:Name="tapInbox"
          Tapped="tapInbox_Tapped"
          NumberOfTapsRequired="1"/>
  </Label.GestureRecognizers>
```

```
    void tapInbox_Tapped(System.Object sender, Microsoft.Maui.Controls.TappedEventArgs e)
    {
        this.GoToAsync($"///{PageType.InboxPage}", true);
    }
```

and i register route like this:

`Routing.RegisterRoute(nameof(PageType.InboxPage), typeof(InboxPage));`

i need help because i don't know how to fix this

**Comment by raselldev** [comment]
Please read this issue @RadekVyM

**Comment by RadekVyM** [comment]
Hi @raselldev,

in `SimpleShell`, navigation works (almost) exactly the same as in the original .NET MAUI `Shell`. Detail pages (pages registered using the `RegisterRoute()` method) **cannot be the only** pages on the navigation stack. See [documentation](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/navigation#invalid-routes) for more info.

For detail pages, try to use something like this instead:

```
this.GoToAsync($"{PageType.InboxPage}", true);
```

**Comment by raselldev** [comment]
It's works! Thanks
