### ISSUE TITLE
[UPDATE] .net 8 support

### ISSUE THREAD

**Issue by shinnthant-lab** [RadekVyM/SimpleToolkit#33]
Dear RadekVyM,

First of all, super thank you for this library and it's super awesome.

Please kindly support .net 8 in near future.
Currently, I'm facing below error at .net 8 project.

![image](https://github.com/RadekVyM/SimpleToolkit/assets/54578974/e6cc27dd-5970-475f-9131-d667b115ba86)

Best Regards,

**Comment by shinnthant-lab** [comment]
But the Method:RemoveLogicalChild still exists in the Maui.Controls 
![image](https://github.com/RadekVyM/SimpleToolkit/assets/54578974/04f9c4a7-ef3b-46b7-affb-2af796688f25)
changed to bool instead of void

**Comment by RadekVyM** [comment]
Hi @shinnthant-lab,

I am glad you like the library. [New version](https://github.com/RadekVyM/SimpleToolkit/releases/tag/v4.0.0) for .NET 8 is released.

**Comment by tolgraven** [comment]
Other stuff I've encountered:

Error from `button.SetValueCore(IsEnabledProperty, true);` in ContentButton (forked and commented it out for now)

Some kind of invalid cast error with few details in IconHandler, both iOS and Android. Done some work investigating this, the current way things are done is apparently obsolete but I can't wrap my head around how the new way actually works.

**Comment by RadekVyM** [comment]
Hi @tolgraven,

thanks for the info. I hope these issues has been resolved with the newest version.

**Comment by shinnthant-lab** [comment]
> Hi @shinnthant-lab,
> 
> I am glad you like the library. [New version](https://github.com/RadekVyM/SimpleToolkit/releases/tag/v4.0.0) for .NET 8 is released.

Thank you so much RadekVyM, let me close the issue now. Thanks
